name: test
on: [ push, pull_request ]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-20.04,   platform: linux-x64 }
          - { os: macos-14,       platform: darwin-arm64 }
          - { os: windows-latest, platform: win32-x64 }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actboy168/setup-luamake@master
      - run: luamake -platform ${{ matrix.platform }}
